app_name: FHIR Code Generator

applications:
  unittest:
    logging:
      level:        DEBUG                  # Can be on of 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
      file:         logs/unittest.log      # Filename of logfile
      use_console:  False                  # Log output to the console?
      backup_count: 5                      # Number of logs to keep
      max_size:     1024                   # Specified in kB (i.e. 1024 means a maximum file size of 1MB)
      format:       "%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s"
  
  generate:
    logging:
      level:        DEBUG                  # Can be on of 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
      file:         logs/generate.log      # Filename of logfile
      use_console:  True                  # Log output to the console?
      backup_count: 5                      # Number of logs to keep
      max_size:     1024                   # Specified in kB (i.e. 1024 means a maximum file size of 1MB)
      format:       "%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s"
    
    clear_model_folder: True
    # ftype: input-stu3/profiles-types.xml
    # fresource: input-stu3/profiles-resources.xml
    ftype: input-r4/profiles-types.xml
    fresource: input-r4/profiles-resources.xml
    output_folder: '../py-fhir/fhir4'
    items:
      - Bundle
      - Patient
      - Observation
      - Composition
      - Questionnaire
      - QuestionnaireResponse
      - Reference
      - Medication
      - MedicationRequest

